apiVersion: apps/v1
kind: Deployment
metadata:
  name: certproj
  labels:
    app: certproj
spec:
  replicas: 2
  selector:
    matchLabels:
      app: certproj
  template:
    metadata:
      labels:
        app: certproj
    spec:
      containers:
      - name: certproj
        image: abheeray/certproj
        ports:
        - containerPort: 9000

---

kind: Service
apiVersion: v1
metadata:
  name: certproj-svc
spec:
  type: NodePort
  selector:
    app: certproj
  ports:
  - protocol: TCP
    port: 80
    
